# Generated by Django 5.1.7 on 2025-03-23 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostique', models.CharField(max_length=100)),
                ('traitment', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=50)),
                ('message_content', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('envoie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_envoyé', to=settings.AUTH_USER_MODEL)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
