# Generated by Django 5.1.7 on 2025-03-23 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('docteur_app', '0001_initial'),
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_app.rendezvous'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='docteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.docteur'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient'),
        ),
    ]
