# Generated by Django 5.1.6 on 2025-03-27 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docteur_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='docteur',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
    ]
