# Generated by Django 5.1.6 on 2025-03-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docteur_app', '0003_remove_prescription_docteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='diagnostique',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='traitment',
            field=models.TextField(),
        ),
    ]
