# Generated by Django 5.1.6 on 2025-03-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='allergiees',
            new_name='allergies',
        ),
    ]
