# Generated by Django 5.1.7 on 2025-03-23 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('etat', models.CharField(choices=[('planifié', 'Planifié'), ('completé', 'Completé'), ('annulé', 'Annulé')], default=('planifié', 'Planifié'), max_length=10)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.docteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.patient')),
            ],
        ),
    ]
